name: Deploy Project

on:
  push:
    branches: ["nasekaylovm-cyber-patch-1"]
  pull_request:
    branches: ["nasekaylovm-cyber-patch-1"]
      
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Update Composer keys
        run: |
          # Сначала обновляем Composer без ключей
          composer self-update
          
          # Затем обновляем ключи через прямой запрос
          curl -sS https://composer.github.io/installer.sig > installer.sig
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          php composer.phar self-update --update-keys
          
          # Удаляем временные файлы
          rm installer.sig
          rm composer.phar

      - name: Fix license in composer.json
        run: |
          sed -i 's/"AGPL-3.0"/"AGPL-3.0-only"/g' composer.json
          composer validate

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction
          composer dump-autoload

      - name: Verify installation
        run: |
          composer diagnose
          php -v
          composer -v
          rm -rf vendor/
          rm -f composer.lock
          composer clear-cache
