name: deploy

on:
  push:
    branches: ["nasekaylovm-cyber-patch-1"]
  pull_request:
    branches: ["nasekaylovm-cyber-patch-1"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, pdo_mysql, xml, curl, json, tokenizer

      - name: Install dependencies
        run: |
          composer clear-cache
          composer install --no-dev --no-scripts --no-interaction --ignore-platform-reqs || true

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 5.129.250.92
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
              cd /var/www/
              rm -rf bootstrapcms
              mkdir -p bootstrapcms
              chown -R bootstrapcms:bootstrapcms /var/www/bootstrapcms
              su - bootstrapcms -c "
              cd /var/www/bootstrapcms
              git clone https://github.com/nasekaylovm-cyber/diplom/tree/nasekaylovm-cyber-patch-1 .
              git checkout nasekaylovm-cyber-patch-1
              composer install --no-dev -o
              cp .env.example .env
              php artisan key:generate
              "

              su - bootstrapcms -c "
              cd /var/www/bootstrapcms
              sed -i 's/DB_DATABASE=.*/DB_DATABASE=bootstrapcms/' .env
              sed -i 's/DB_USERNAME=.*/DB_USERNAME=bootstrapcms_user/' .env
              sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/' .env
              "
             
              su - bootstrapcms -c "
              cd /var/www/bootstrapcms
              php artisan migrate --force
              php artisan config:cache
              php artisan route:cache
              php artisan view:cache
              npm install --production
              "
              
              chown -R bootstrapcms:www-data /var/www/bootstrapcms/storage
              chown -R bootstrapcms:www-data /var/www/bootstrapcms/bootstrap/cache
              chmod -R 755 /var/www/bootstrapcms/storage
              chmod -R 755 /var/www/bootstrapcms/bootstrap/cache

              systemctl reload nginx
          
