name: Deploy Project

on:
  push:
    branches: ["nasekaylovm-cyber-patch-1"]
  pull_request:
    branches: ["nasekaylovm-cyber-patch-1"]
      
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, dom, curl, xml, json

      - name: Install dependencies
        run: |
            rm -rf vendor/
            rm -f composer.lock
            composer diagnose
            composer install \
              --prefer-dist \
              --no-interaction \
              --no-plugins \
              --no-scripts \
              --optimize-autoloader
      
      - name: Enable scripts and autoload
        run: |
            composer dump-autoload
            composer install --no-interaction --optimize-autoloader
      
      - name: Prepare environment
        run: |
              cp .env.example .env
              php artisan key:generate
              php artisan config:clear
              php artisan cache:clear
