name: Deploy Project

on:
  push:
    branches: ["nasekaylovm-cyber-patch-1"]
  pull_request:
    branches: ["nasekaylovm-cyber-patch-1"]
      
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Update Composer
        run: |
          composer self-update
          composer self-update --update-keys

      - name: Fix license in composer.json
        run: |
          sed -i 's/"AGPL-3.0"/"AGPL-3.0-only"/g' composer.json
          composer validate

      - name: Clear Composer cache
        run: composer clear-cache

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction
          composer dump-autoload

      - name: Verify installation
        run: |
          composer diagnose
          php -v
          composer -v

      - name: Cleanup
        run: |
          rm -rf vendor/
          rm -f composer.lock
          composer clear-cache
