name: CD BILD_DEP_DAST

on:
  push:
    branches: [ nasekaylovm-cyber-patch-1 ]
  pull_request:
    branches: [ nasekaylovm-cyber-patch-1 ]


jobs:

  dast-scan:
    name: DAST - Dynamic Application Security Testing
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Wait for application to be ready
      run: sleep 60

    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://5.129.250.92'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'

    - name: Nmap Security Scan
      run: |
        sudo apt update
        sudo apt install -y nmap
        nmap -sV --script vuln 5.129.250.92

    - name: SSL/TLS Scan
      uses: wearerequired/ssl-check-action@v1
      with:
        domain: 5.129.250.92
        port: 443
