name: CD BILD_DEP_DAST

on:
  push:
    branches: [ nasekaylovm-cyber-patch-1 ]
  pull_request:
    branches: [ nasekaylovm-cyber-patch-1 ]


jobs:
  build-and-test:
    name: Build Docker Image and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t bootstrap-cms:latest .
        
    - name: Run security scan on Docker image
      run: |
        trivy image --exit-code 0 --severity HIGH,CRITICAL --format sarif -o trivy-image-results.sarif bootstrap-cms:latest
    - name: Upload Docker image scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-image-results.sarif'

    - name: Run container tests
      run: |
        docker run -d --name test-cms -p 8080:80 bootstrap-cms:latest
        sleep 30
        curl -f http://localhost:8080 || exit 1
        docker stop test-cms
        docker rm test-cms
 
  deploy-to-server:
    name: Deploy to Production Server
    runs-on: [self-hosted, linux, x64]
    needs: build-and-test
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      run: |
        chmod +x .github/scripts/deploy.sh
        ./.github/scripts/deploy.sh

  dast-scan:
      name: DAST - Dynamic Application Security Testing
      runs-on: ubuntu-latest
      
      
      steps:
      - name: Wait for application to be ready
        run: sleep 60
  
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://5.129.250.92'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
  
      - name: Nmap Security Scan
        run: |
          sudo apt update
          sudo apt install -y nmap
          nmap -sV --script vuln 5.129.250.92
  
      - name: SSL/TLS Scan
        uses: wearerequired/ssl-check-action@v1
        with:
          domain: 5.129.250.92
          port: 443
