name: CI - SAST and Security Checks

on:
  push:
    branches: [ nasekaylovm-cyber-patch-1 ]
  pull_request:
    branches: [ nasekaylovm-cyber-patch-1 ]

jobs:
  security-checks:
    name: Security Checks - Secrets and Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect secrets in repository
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml
        redact: true
        verbose: true

    - name: Check for vulnerable dependencies
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  sast-analysis:
    name: SAST - Static Application Security Testing
    runs-on: ubuntu-latest
    needs: security-checks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Semgrep SAST Scan
      uses: returntocorp/semgrep-action@v1
      continue-on-error: true
      with:
        config: p/security-audit
        # Отключаем SARIF и используем только консольный вывод
        output: semgrep-results.txt
        format: txt

    - name: Display Semgrep Results
      run: |
        if [ -f "semgrep-results.txt" ]; then
          echo "=== Semgrep Results ==="
          cat semgrep-results.txt
        else
          echo "No Semgrep results file found"
        fi


    - name: JavaScript Security Scan
      run: |
        if [ -f "package.json" ]; then
          echo "Running JavaScript security checks..."
          npm install --force --silent
          npm audit --audit-level moderate || {
            echo "NPM audit found vulnerabilities"
            exit 0
          }
        else
          echo "No package.json found, skipping JavaScript security scan"
        fi

    - name: Bandit Python SAST
      run: |
        if [ -f "requirements.txt" ] || [ -f "setup.py" ]; then
          pip install bandit
          bandit -r . -f json -o bandit-results.json || true
        fi
