name: CI - SAST and Security Checks

on:
  push:
    branches: [ nasekaylovm-cyber-patch-1 ]
  pull_request:
    branches: [ nasekaylovm-cyber-patch-1 ]

jobs:
  security-checks:
    name: Security Checks - Secrets and Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect secrets in repository
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml
        redact: true
        verbose: true

    - name: Check for vulnerable dependencies
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  sast-analysis:
    name: SAST - Static Application Security Testing
    runs-on: ubuntu-latest
    needs: security-checks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Semgrep scan
      id: semgrep
      continue-on-error: true
      run: |
        semgrep --config=p/security-audit --sarif --output=semgrep-results.sarif .

    - name: Check if SARIF file contains results
      id: check_sarif
      run: |
        if [ -f "semgrep-results.sarif" ]; then
          # Проверяем, содержит ли файл реальные результаты (не пустой runs array)
          if jq -e '.runs[] | select(.results != null and .results != [])' semgrep-results.sarif > /dev/null 2>&1; then
            echo "has_findings=true" >> $GITHUB_OUTPUT
            echo "SARIF file contains findings"
          else
            echo "has_findings=false" >> $GITHUB_OUTPUT
            echo "SARIF file exists but contains no findings"
            rm -f semgrep-results.sarif
          fi
        else
          echo "has_findings=false" >> $GITHUB_OUTPUT
          echo "SARIF file does not exist"
        fi

    - name: Upload Semgrep results only if contains findings
      if: steps.check_sarif.outputs.has_findings == 'true'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'semgrep-results.sarif'

    - name: PHP Security Check
      run: |
        if [ -f "composer.json" ]; then
          composer install --no-dev
          wget https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.6/local-php-security-checker_2.0.6_linux_amd64
          chmod +x local-php-security-checker_2.0.6_linux_amd64
          ./local-php-security-checker_2.0.6_linux_amd64
        fi

    - name: JavaScript Security Scan
      run: |
        if [ -f "package.json" ]; then
          npm ci
          npm audit --audit-level moderate
        fi

    - name: Bandit Python SAST
      run: |
        if [ -f "requirements.txt" ] || [ -f "setup.py" ]; then
          pip install bandit
          bandit -r . -f json -o bandit-results.json || true
        fi
