name: Secure Deploy Pipeline

stages:
  - testing (SAST)
  - deploy
  - testing (DAST)


on:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]

jobs:

  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: Install Composer dependencies
        run: composer install --prefer-dist
      # SAST для PHP с помощью Semgrep
      - name: Run Semgrep SAST Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/security-audit # Набор правил для security audit
        continue-on-error: true # Не тормозим из-за ошибок.
      # Вывод Semgrep в SARIF и загружаем в GitHub Code Scanning
      - name: Upload Semgrep results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always() # Результаты даже если шаг шмякнулся
        with:
          sarif_file: semgrep.sarif
