name: CI/CD Security Pipeline

on:
  push:
    branches: [ "naster" ]
  pull_request:
    branches: [ "master" ]

jobs:

  sast:
    name: SAST Scan with Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep SAST Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/security-audit # Набор правил для поиска уязвимостей
          sarifUpload: true
        continue-on-error: true

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests (if any exist)
        run: vendor/bin/phpunit --colors=always

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: build
    
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
           
            cd /home/cms
            git pull origin master
            composer install --no-dev --optimize-autoloader
           
            sudo systemctl reload nginx

  dast:
    name: DAST Scan with ZAP
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://5.129.250.92'
          rules_file_name: 'All'
          cmd_options: '-a'
          report_html: 'report.html'
          report_md: 'report.md'

      - name: Upload ZAP HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-html-report
          path: report.html

      - name: Upload ZAP Markdown report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-md-report
          path: report.md
